INPUT:
  NUM_CAPTIONS_PER_IMAGE_TRN: 5
  NUM_CAPTIONS_PER_IMAGE_DEV: 20

DATASET:
  NAME: 'COCO'
  DATA_DIR: '/mnt/disk6T/Data/Research/Multi-Modal-Pretraining/2020-Oscar-ECCV/data/coco_ir_paddle/'
  TRAIN: 'train'
  DEV: 'minival'
  TEST: 'test'

OUTPUT:
  SAVE_NAME: 'finetune_retrieval'
  NUM_LABELS: 2

PRETRAINED:
  DIR: '/mnt/disk6T/Data/Research/Multi-Modal-Pretraining/2020-Oscar-ECCV/pretrained_model/paddle_version'

EVAL:
  EVAL_CAPTION_INDEX_FILE: 'minival_caption_indexs_top20.pd'

